# Generated by Django 5.2.9 on 2026-01-11 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название жанра"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание жанра"
                    ),
                ),
                (
                    "lastfm_tag",
                    models.CharField(
                        blank=True,
                        help_text="Соответствующий тег в Last.fm API",
                        max_length=100,
                        null=True,
                        verbose_name="Тег в Last.fm",
                    ),
                ),
                (
                    "lastfm_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Страница в Last.fm"
                    ),
                ),
                (
                    "track_count",
                    models.IntegerField(default=0, verbose_name="Количество треков"),
                ),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Популярный жанр"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "ordering": ["-track_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Имя исполнителя"),
                ),
                (
                    "lastfm_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Страница в Last.fm"
                    ),
                ),
                (
                    "lastfm_listeners",
                    models.IntegerField(
                        default=0, verbose_name="Количество слушателей"
                    ),
                ),
                (
                    "lastfm_playcount",
                    models.IntegerField(
                        default=0, verbose_name="Количество прослушиваний"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание исполнителя"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL изображения",
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, verbose_name="Популярный исполнитель"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True,
                        related_name="artists",
                        to="catalog.genre",
                        verbose_name="Жанры",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исполнитель",
                "verbose_name_plural": "Исполнители",
                "ordering": ["-lastfm_listeners", "name"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название трека"),
                ),
                (
                    "lastfm_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Страница в Last.fm"
                    ),
                ),
                (
                    "lastfm_listeners",
                    models.IntegerField(
                        default=0, verbose_name="Количество слушателей"
                    ),
                ),
                (
                    "lastfm_playcount",
                    models.IntegerField(
                        default=0, verbose_name="Количество прослушиваний"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Продолжительность (секунды)",
                    ),
                ),
                (
                    "album",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Альбом"
                    ),
                ),
                (
                    "tags_json",
                    models.TextField(
                        blank=True,
                        help_text="Теги и жанры трека в формате JSON",
                        null=True,
                        verbose_name="Теги (JSON)",
                    ),
                ),
                (
                    "lastfm_data",
                    models.TextField(
                        blank=True,
                        help_text="Полные данные из Last.fm API в формате JSON",
                        null=True,
                        verbose_name="Данные Last.fm (JSON)",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL изображения",
                    ),
                ),
                (
                    "is_reference",
                    models.BooleanField(
                        default=False,
                        help_text="Использовать как референс для анализа жанра",
                        verbose_name="Референс-трек",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="catalog.artist",
                        verbose_name="Исполнитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Трек",
                "verbose_name_plural": "Треки",
                "ordering": ["-lastfm_playcount", "title"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("bio", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "lastfm_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "favorite_genres",
                    models.ManyToManyField(blank=True, to="catalog.genre"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("genre", "Жанр"),
                            ("track", "Трек"),
                            ("artist", "Исполнитель"),
                        ],
                        default="genre",
                        max_length=20,
                        verbose_name="Тип элемента",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        help_text="ID жанра, трека или исполнителя",
                        max_length=255,
                        verbose_name="ID элемента",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
                "ordering": ["-created_at"],
                "unique_together": {("user", "item_type", "item_id")},
            },
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(fields=["name"], name="catalog_art_name_36791d_idx"),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(
                fields=["lastfm_listeners"], name="catalog_art_lastfm__b57c98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(fields=["title"], name="catalog_tra_title_d1c714_idx"),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["lastfm_playcount"], name="catalog_tra_lastfm__057a85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["is_reference"], name="catalog_tra_is_refe_8fce48_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("title", "artist"), name="unique_track_per_artist"
            ),
        ),
    ]
