# Generated by Django 5.2.9 on 2025-12-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="track",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="track",
            name="album_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="album_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="duration_ms",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="track",
            name="popularity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="track",
            name="spotify_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="audio_features",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="preview_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="spotify_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
